wandb_version: 1

dk:
  value: 32
dv:
  value: 32
epochs:
  value: 100
features_length:
  value: 16
learning_rate:
  value: 0.0090798906278385
num_blocks:
  value: 3
num_heads:
  value: 4
optimizer:
  value: adam
