wandb_version: 1

architecture:
  desc: null
  value: CNN
val_fold:
  desc: null
  value: 4
n_classes:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708267521.884123
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 13
      - 16
      - 23
      - 37
      4: 3.9.16
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 1
fc_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.006731446679930541
optimizer:
  desc: null
  value: adam
trainable_params:
  desc: null
  value: 2116634
non_trainable_params:
  desc: null
  value: 0
total_params:
  desc: null
  value: 2116634
