wandb_version: 1

dk:
  value: 32
dv:
  value: 32
epochs:
  value: 100
features_length:
  value: 16
learning_rate:
  value: 0.004784907677626895
num_blocks:
  value: 3
num_heads:
  value: 1
optimizer:
  value: adam
