wandb_version: 1

dk:
  desc: null
  value: 32
dv:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
features_length:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.008045014585191029
num_blocks:
  desc: null
  value: 2
num_heads:
  desc: null
  value: 4
optimizer:
  desc: null
  value: sgd
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708362306.576953
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.10
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
trainable_params:
  desc: null
  value: 55803
non_trainable_params:
  desc: null
  value: 0
total_params:
  desc: null
  value: 55803
