wandb_version: 1

dk:
  value: 32
dv:
  value: 64
epochs:
  value: 100
features_length:
  value: 16
learning_rate:
  value: 0.005550070515547667
num_blocks:
  value: 3
num_heads:
  value: 2
optimizer:
  value: sgd
