wandb_version: 1

dk:
  value: 64
dv:
  value: 32
epochs:
  value: 100
features_length:
  value: 32
learning_rate:
  value: 0.001268355627769352
num_blocks:
  value: 3
num_heads:
  value: 1
optimizer:
  value: adam
