wandb_version: 1

dk:
  value: 32
dv:
  value: 64
epochs:
  value: 100
features_length:
  value: 16
learning_rate:
  value: 0.006906999903963381
num_blocks:
  value: 3
num_heads:
  value: 1
optimizer:
  value: adam
