wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708345908.7339
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 2
      - 23
      - 37
      4: 3.10.10
      5: 0.16.3
      8:
      - 1
      - 5
      10:
      - 3
      13: linux-x86_64
dk:
  desc: null
  value: 64
dv:
  desc: null
  value: 64
epochs:
  desc: null
  value: 100
features_length:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0010968132686253584
num_blocks:
  desc: null
  value: 2
num_heads:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
