wandb_version: 1

dk:
  value: 64
dv:
  value: 64
epochs:
  value: 100
features_length:
  value: 32
learning_rate:
  value: 0.006514149114191085
num_blocks:
  value: 3
num_heads:
  value: 2
optimizer:
  value: adam
