wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
dropout:
  desc: null
  value: 0.1
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: UrabnSound8K
epochs:
  desc: null
  value: 10
val_fold:
  desc: null
  value: 2
n_classes:
  desc: null
  value: 10
trainable_params:
  desc: null
  value: 8416538
non_trainable_params:
  desc: null
  value: 0
total_params:
  desc: null
  value: 8416538
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708263230.744319
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
