wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708278397.879037
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 5
      - 14
      - 23
      4: 3.9.16
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 2
dropout:
  desc: null
  value: 0.4
fc_size:
  desc: null
  value: 512
optimizer:
  desc: null
  value: sgd
learning_rate:
  desc: null
  value: 0.009086419460243689
