wandb_version: 1

dk:
  value: 64
dv:
  value: 32
epochs:
  value: 100
features_length:
  value: 16
learning_rate:
  value: 0.008143519900506274
num_blocks:
  value: 2
num_heads:
  value: 2
optimizer:
  value: adam
