wandb_version: 1

dropout:
  desc: null
  value: 0.4
epochs:
  desc: null
  value: 2
fc_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.009168167602527906
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708281239.782388
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
trainable_params:
  desc: null
  value: 4216602
non_trainable_params:
  desc: null
  value: 0
total_params:
  desc: null
  value: 4216602
