wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708277828.041837
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      10:
      - 3
      13: windows-amd64
dropout:
  desc: null
  value: 0.4
epochs:
  desc: null
  value: 2
fc_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.005283844933718335
optimizer:
  desc: null
  value: sgd
