wandb_version: 1

dk:
  value: 32
dv:
  value: 64
epochs:
  value: 100
features_length:
  value: 16
learning_rate:
  value: 0.0038478401907387377
num_blocks:
  value: 2
num_heads:
  value: 4
optimizer:
  value: adam
