wandb_version: 1

dk:
  value: 64
dv:
  value: 64
epochs:
  value: 100
features_length:
  value: 16
learning_rate:
  value: 0.0017778114516006705
num_blocks:
  value: 3
num_heads:
  value: 4
optimizer:
  value: sgd
