wandb_version: 1

dk:
  value: 32
dv:
  value: 64
epochs:
  value: 100
features_length:
  value: 32
learning_rate:
  value: 0.0022377491391979954
num_blocks:
  value: 3
num_heads:
  value: 4
optimizer:
  value: sgd
